name: Callable Workflow
on:
  workflow_call:
    inputs: #liste deine params auf
      jdk_version_0: #frei benannter Param
        description: Give us the a version for the JDK. Used in Matrix-workflow
        type: string
      jdk_version_1: #frei benannter param
        description: Give us another JDK version
        required: false
        type: string
      ubuntu_version_0: #frei benannter param
        description: Give us a ubuntu version distro
        type: string
      ubuntu_version_1: #frei benannter param
        description: Give us another ubuntu version distro
        required: false
        type: string
    outputs:
      log-output:
        description: Log output as return value
        value: steps.jdk_setup_and_cache.outputs.my-log-file-output
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Context-Info
        id: echo-step
        run: echo "{{toJSON(github)}}"
      - name: Conditional Step
        if: success()
        run: echo "success, run this stuff"
  test-job:
    # continue-on-error: true #falls einige kombinationen fehlschlagen
    container:
      image: openjdk
    env:
      de.ayalama.variable.to.override: 'job-level'
    runs-on: ubuntu-latest
    outputs:
      my-log-file-output: ${{steps.output_file.outputs.my-log-file}}
    steps:
      - name: hol dir Actions
        continue-on-error: true
        uses: actions/checkout@v3
      - name: Set up JDK 17
        id: jdk_setup_and_cache
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven' #Alternativ auch so Cachebar - ist aber ein feauture von actionsS/setup-java
      - name: Test with Maven
        id: maven_test
        run: mvn -B test
      - name: Output file
        id: output_file
        run: find logs/*.log -type f -execdir echo 'my-log-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload Artifacts - Save Logs
        uses: actions/upload-artifact@v3
        with:
          name: 'logfiles'
          path: './logs/actions.log'
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: 'logfiles' #muss namentlich gleich sein wie der upload with:name
      - name: Check if JDK Cache hit
        if: steps.jdk_setup_and_cache.outputs.cache-hit == 'true' #cache-hit gives us string
        run: echo "JDK wurde gecached"