name: Checkout Workflow
on:
  push: #bei push
    branches:
      - 'master'
      - 'feature/**'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'AlKYala/Github-Actions-Tut'