name: Deployment Workflow
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
    paths: #uebereinstimmung ordner / dateiname
      - '**.java'
      - '**.yml'
      - '**.properties'
    tags: #Tagname muss uebereinstimmen
      - '**.**'
  pull_request:
    types: [opened, closed, synchronized, reopened, unlocked, edited]
    branches:
      - 'master'
      - 'develop**'
  workflow_dispatch:
jobs:
  #reference here - java workflows
  call_java_workflow: #Tests my java app, builds it and uses it for docker-compose - this job and its steps are defined somewhere else
      uses: ./.github/workflows/java_workflow.yml
      with:
        jdk_version: '17'
        ubuntu_version: 'ubuntu-latest'



