name: Deployment Workflow
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
    paths: #uebereinstimmung ordner / dateiname
      - '**.java'
      - '**.yml'
      - '**.properties'
    tags: #Tagname muss uebereinstimmen
      - '**.**'
  pull_request:
    types: [opened, closed, synchronized, reopened, unlocked, edited]
    branches:
      - 'master'
      - 'develop**'
  workflow_dispatch:
jobs:
  test-and-build-jar-and-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Java so you can Test and Build later
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test with Maven
        id: maven_test
        run: mvn -B test
      - name: Build
        id: maven_build
        run: mvn clean install -P local #local als Profil. Muss noch geaendert werden
      - name: Find target folder
        run: |
          cd target
          ls -a



