name: Deployment Workflow
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
    paths: #uebereinstimmung ordner / dateiname
      - '**.java'
      - '**.yml'
      - '**.properties'
    tags: #Tagname muss uebereinstimmen
      - '**.**'
  pull_request:
    types: [opened, closed, synchronized, reopened, unlocked, edited]
    branches:
      - 'master'
      - 'develop**'
  workflow_dispatch:
jobs:
  #reference here - java workflows
  call_java_workflow: #Tests and Builds .jar-File
    runs-on: ubuntu-latest
    steps:
      - name: Test And Build
        uses: ./.github/workflows/java_workflow.yml
        with:
          jdk_version: '17'
          ubuntu_version: 'ubuntu-latest'
      - name: Run Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker/docker-compose.yml"


