name: Java Workflow and docker compose
on:
  workflow_call:
    inputs: #liste deine params auf
      jdk_version: #frei benannter Param
        description: Give us the a version for the JDK. Used in Matrix-workflow
        type: string
      ubuntu_version: #frei benannter param
        description: Give us a ubuntu version distro
        type: string
    outputs:
      log-output:
        description: Log output as return value
        value: steps.jdk_setup_and_cache.outputs.my-log-file-output
jobs:
  test-and-build-jar-and-docker-compose:
    runs-on: ${{inputs.ubuntu_version}}
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
      - name: Setup Java so you can Test and Build later
        uses: actions/setup-java@v3
        with:
          java-version: ${{inputs.jdk_version}}
          distribution: 'adopt'
      - name: Test with Maven
        id: maven_test
        run: mvn -B test
      - name: Build
        id: maven_build
        run: mvn clean install -P local #local als Profil. Muss noch geaendert werden
      - name: Find target folder
        run: |
          cd target
          ls -a
      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
      - name: 'Login via Azure CLI'
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

