name: Conditions und continue-on-error
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
    paths: #uebereinstimmung ordner / dateiname
      - '**.java'
      - '**.yml'
      - '**.properties'
    tags: #Tagname muss uebereinstimmen
      - '**.**'
  pull_request:
    types: [opened, closed, synchronized, reopened, unlocked, edited]
    branches:
      - 'master'
      - 'develop**'
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
env:
  de.ayalama.variable.to.override: 'workflow-level'
jobs:
  #reference here - java workflows
  call_java_workflow:
      uses: ./.github/workflows/reusable_workflow.yml
  read-output-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Auslesen von Output
        run: echo "${{needs.test-job.outputs.my-log-file-output}}"
  read-secret-variable:
    environment: foo-env
    runs-on: ubuntu-latest
    steps:
      - name: Secret Varaible Auslesen
        run: echo "${{secrets.SECRET_TEST}}"
      - name: Secret Varaible aus Environment auslesen
        run: echo "${{secrets.SECRET_IN_ENV}}"
  job-to-test-conditions:
    runs-on: ubuntu-latest
    needs:
      - test-job
    name: another-job-condition
    if: cancelled()
    steps:
      - name: echostep
        run: echo "success, run this stuff"



