name: Example
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
  schedule:
    - cron: '*/5 * * * *'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Context-Info
        run: echo "{{toJSON(github)}}"
  test-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B test