name: Callable Workflow that uses a custom action
on:
  workflow_call:
    inputs: #liste deine params auf
      jdk_version: #frei benannter Param
        description: Give us the a version for the JDK. Used in Matrix-workflow
        type: string
      ubuntu_version: #frei benannter param
        description: Give us a ubuntu version distro
        type: string
    outputs:
      log-output:
        description: Log output as return value
        value: steps.jdk_setup_and_cache.outputs.my-log-file-output
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Context-Info
        id: echo-step
        run: echo "{{toJSON(github)}}"
      - name: Conditional Step
        if: success()
        run: echo "success, run this stuff"
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # damit wir auf dateien im Repo zugreifen koennen
      - uses: ./.github/actions/test-java-app
        with:
          jdk_version: '${{ inputs.jdk_version }'
          ubuntu-version: '${{ inputs.ubuntu_version }'