name: Workflow that uses a mongo db image
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
    paths: #uebereinstimmung ordner / dateiname
      - '**.java'
      - '**.yml'
      - '**.properties'
    tags: #Tagname muss uebereinstimmen
      - '**.**'
  pull_request:
    types: [opened, closed, synchronized, reopened, unlocked, edited]
    branches:
      - 'master'
      - 'develop**'
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
env:
  de.ayalama.variable.to.override: 'workflow-level'
jobs:
  #reference here - java workflows
  call_java_workflow:
      uses: ./.github/workflows/reusable_workflow.yml
      with:
        jdk_version_0: '17'
        jdk_version_1: '19'
        ubuntu_version_0: 'ubuntu-latest'
        ubuntu_version_1: 'ubuntu-20.04'
  job_to_check_output_of_called_workflow:
    needs: call_java_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print output of previous job
        run: echo "${{ needs.call_java_workflow.outputs.log-output }}"
  read-secret-variable:
    environment: foo-env
    runs-on: ubuntu-latest
    steps:
      - name: Secret Varaible Auslesen
        run: echo "${{secrets.SECRET_TEST}}"
      - name: Secret Varaible aus Environment auslesen
        run: echo "${{secrets.SECRET_IN_ENV}}"
  job-to-test-conditions:
    runs-on: ubuntu-latest
    needs:
      - call_java_workflow
    name: another-job-condition
    if: cancelled()
    steps:
      - name: echostep
        run: echo "success, run this stuff"
  mongojob: # this job does not do anything but get mongo
    runs-on: ubuntu-latest
    container:
      image: mongo



